apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: acme-users-mongo-pass
spec:
  provider: vault
  secretObjects:
  - data:
    - key: password
      objectName: users-mongo-password
    secretName: users-mongo-pass
    type: Opaque
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "acme"
    objects: |
      - objectName: "users-mongo-password"
        secretPath: "acme/data/users-mongo-pass"
        secretKey: "password"
