apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: acme-redis-pass
spec:
  provider: vault
  secretObjects:
  - data:
    - key: password
      objectName: redis-password
    secretName: redis-pass
    type: Opaque
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "acme"
    objects: |
      - objectName: "redis-password"
        secretPath: "acme/data/redis-pass"
        secretKey: "password"